### ISSUE TITLE
Weekly Scrum - 21st - 25

### ISSUE THREAD

**Issue by jaymccracken** [EveningStarlight/SYSC_4806_Project#51]
The start of the weekly scrum, make sure to talk about:

```md
## This week

## Next Week

## Difficulties
```

**Comment by imran1503** [comment]
This week I finished dynamically creating the page that displays all the users surveys and created a button for each that next milestone will lead to a page showing the table in detail as well as the histograms and charts from the answers collected. 

I also created the middle page where the user is allowed to select what survey they are answering. 

The main difficulty that I encountered was trouble with timeline concerning the database, so I was delayed slightly.

**Comment by EveningStarlight** [comment]
## This week

Created the survey dynamically from the given JSON #10 
Made GitHub issues Templates #6125731
Created individual Survey pages using URL ids #54 
Created the local Mocked database data.json #57 
Dynamically populated tables with surveys from the data.json #58 
Saved answers to local mock #63 
Provided help for other code

## Next Week

Will pick topics remaining after others select.

## Difficulties

Database still only mocked

**Comment by jaymccracken** [comment]
## This week
Made survey into json format when submitted
Made new thankyou landing pages for after creating a survey and then answering a survey
Made answers into the json format when submitted
made a dynamic table to show all the surveys that have answers
Made table of the answers of a table

## Next Week
Will pick topics with others 

## Difficulties
Database doesnt like us

**Comment by mattman555** [comment]
THIS WEEK
Made functionality to push to json object database to save data
studied and researched how to setup the backend for proper persistence of data

NEXT WEEK
Working on setting up heroku with node server to act as backend
